name: Unzip files

on:
  push:
    paths:
      - "your-zip-file.zip"  # Replace with your actual zip file name

jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract ZIP file
      run: |
        unzip your-zip-file.zip -d extracted/  # Replace with your ZIP file name
        git add extracted/
        git commit -m "Extract ZIP file contents"
        git push
